import assert from'node:assert/strict';import test from'node:test';import{build}from'esbuild';const b=await build({stdin:{contents:"export * from './app/pit-lab/pitLabProduction';",resolveDir:process.cwd()},bundle:true,write:false,platform:'node',format:'esm'});const p=await import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));
test('production lab includes duel expansions and reports exact oriented coverage',()=>{assert.equal(p.PIT_LAB_FIGHTER_IDS.length,14);for(const id of ['tracker','greyback']){assert(p.PIT_LAB_FIGHTER_IDS.includes(id));const c=p.getPitLabCoverage(id);assert.equal(c.clips,28);assert.equal(c.rightClips,14);assert.equal(c.leftClips,14);assert.equal(c.sourcePages,8);}const j=p.getPitLabCoverage('jungle-hunter');assert.equal(j.clips,13);assert.equal(j.drawings,34);assert.equal(j.rightClips,6);assert.equal(j.leftClips,7);assert.equal(p.getPitLabCoverage('falconer').atlasCount,0);});
test('lab samples inspect exact facing, reaction time and attack phase instead of mirroring',()=>{for(const id of ['tracker','greyback','jungle-hunter'])for(const d of p.getPitLabDefinitions(id))for(const c of d.atlas.clips)for(let n=0;n<c.frames.length;n++){const s=p.createPitLabFrame(id,c,n);assert.equal(s.fighter.definitionId,id);assert.equal(s.fighter.facing,c.facing==='right'?1:-1);assert.equal(s.index,n);assert.equal(s.combat.frame,s.tick);if(c.id==='pit.stand.hitstun')assert.equal(s.fighter.stunFrames,40-s.tick);if(c.id==='crouch')assert.equal(s.fighter.crouching,true);if(c.id==='walk')assert.equal(Math.sign(s.fighter.velocityX),s.fighter.facing);const phase=c.id.split('.').at(-1);if(['startup','active','recovery'].includes(phase))assert.equal(s.fighter.phase,phase);}});

test('playback uses real engine phase time and the renderer agrees at every tick',async()=>{
 const b=await build({stdin:{contents:"export {describePitHunterSpriteMotion,resolvePitHunterSpriteFrame} from './app/game/hunterSpriteMotion';export {PIT_FIGHTERS} from './app/game/systems/pitCombat';",resolveDir:process.cwd()},bundle:true,write:false,platform:'node',format:'esm'});const engine=await import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));
 const tracker=p.getPitLabDefinitions('tracker')[0].atlas.clips.find(c=>c.id==='pit.stand.light.recovery'&&c.facing==='right');assert.deepEqual(tracker.frames.map((_,i)=>p.getPitLabFrameTicks('tracker',tracker,i)),[6,5]);
 for(const id of p.PIT_LAB_FIGHTER_IDS)for(const d of p.getPitLabDefinitions(id))for(const clip of d.atlas.clips){
  const match=/^pit\.stand\.(light|medium|heavy)\.(startup|active|recovery)$/.exec(clip.id);if(!match)continue;
  const durations=clip.frames.map((_,i)=>p.getPitLabFrameTicks(id,clip,i)),total=durations.reduce((a,b)=>a+b,0);assert.equal(total,engine.PIT_FIGHTERS[id].attacks[match[1]][match[2]],id+' '+clip.id);
  const sample=p.createPitLabFrame(id,clip,0),actionStart=sample.fighter.action.frame;let cursor,expected=0,boundary=durations[0];
  for(let tick=0;tick<total;tick++){while(tick>=boundary&&expected<durations.length-1)boundary+=durations[++expected];sample.fighter.action.frame=actionStart+tick;const motion=engine.describePitHunterSpriteMotion(sample.fighter,tick,cursor);assert(motion);cursor=motion.cursor;const actual=engine.resolvePitHunterSpriteFrame(d.atlas,motion);assert(actual);assert.equal(actual.frame.frameIndex,expected,id+' '+clip.id+' tick'+tick);}
 }
 const hit=p.getPitLabDefinitions('tracker')[0].atlas.clips.find(c=>c.id==='pit.stand.hitstun');assert.equal(hit.frames.reduce((sum,_,i)=>sum+p.getPitLabFrameTicks('tracker',hit,i),0),40);
});
