"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import LegacyPitAnimationLab from './PitAnimationLab';
import {PIT_FIGHTERS,type PitFighterId} from '../game/systems/pitCombat';
import {loadPitSpriteSheetAnimations,resolvePitSpriteSheetAnimation,drawPitSpriteSheetAnimation,type PitSpriteSheetAnimationBank} from '../game/pitSpriteSheetAnimation';
import {PIT_LAB_FIGHTER_IDS,getPitLabDefinitions,getPitLabCoverage,createPitLabFrame,getPitLabFrameTicks} from './pitLabProduction';
import styles from './PitAnimationLab.module.css';

export default function PitProductionAnimationLab(){
 const[fighterId,setFighterId]=useState<PitFighterId>('jungle-hunter'),[atlasId,setAtlasId]=useState(''),[clipId,setClipId]=useState('idle'),[facing,setFacing]=useState<'right'|'left'>('right'),[index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[showLegacy,setShowLegacy]=useState(false),[speed,setSpeed]=useState(.5),[message,setMessage]=useState('');
 const[loaded,setLoaded]=useState<{key:string;bank:PitSpriteSheetAnimationBank}|null>(null);
 const canvasRef=useRef<HTMLCanvasElement>(null), definitions=useMemo(()=>getPitLabDefinitions(fighterId),[fighterId]);
 const definition=definitions.find(d=>d.atlas.id===atlasId)??definitions[0],key=fighterId+':'+(definition?.atlas.id??'none');
 const bank=loaded?.key===key?loaded.bank:null,coverage=getPitLabCoverage(fighterId);
 const clipIds=[...new Set(definition?.atlas.clips.filter(c=>c.status==='validated').map(c=>c.id)??[])];
 const selectedId=clipIds.includes(clipId)?clipId:clipIds[0],clip=definition?.atlas.clips.find(c=>c.id===selectedId&&c.facing===facing&&c.status==='validated');
 const currentIndex=Math.min(index,Math.max(0,(clip?.frames.length??1)-1));
 const sample=useMemo(()=>clip?createPitLabFrame(fighterId,clip,currentIndex):null,[fighterId,clip,currentIndex]);
 const resolved=useMemo(()=>{if(!bank||!clip||!sample)return null;const baseline=createPitLabFrame(fighterId,clip,0);resolvePitSpriteSheetAnimation(bank,baseline.fighter,{simulationFrame:0,combat:baseline.combat});return resolvePitSpriteSheetAnimation(bank,sample.fighter,{simulationFrame:sample.tick,combat:sample.combat});},[bank,clip,sample,fighterId]);
 const status=!definition?'missing-atlas':!clip?'missing-clip':!bank?'loading':resolved?'ready':'unavailable';
 useEffect(()=>{if(!definition)return;const abort=new AbortController();void loadPitSpriteSheetAnimations([fighterId],[definition],{signal:abort.signal}).then(bank=>{if(!abort.signal.aborted)setLoaded({key,bank});});return()=>abort.abort();},[definition,fighterId,key]);
 useEffect(()=>{if(!playing||!clip||status!=='ready')return;const delay=Math.max(16,getPitLabFrameTicks(fighterId,clip,currentIndex)/60*1000/speed);const timer=window.setTimeout(()=>setIndex(n=>(n+1)%clip.frames.length),delay);return()=>window.clearTimeout(timer);},[playing,clip,status,currentIndex,speed,fighterId]);
 useEffect(()=>{const canvas=canvasRef.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;ctx.clearRect(0,0,960,540);ctx.fillStyle='#0d1818';ctx.fillRect(0,0,960,540);ctx.strokeStyle='#64845d';ctx.beginPath();ctx.moveTo(60,465);ctx.lineTo(900,465);ctx.stroke();if(status==='ready'&&bank&&sample){ctx.save();ctx.translate(480,465);ctx.scale(2.5,2.5);ctx.translate(-480,-465);drawPitSpriteSheetAnimation(ctx,bank,sample.fighter,465,{simulationFrame:sample.tick,combat:sample.combat});ctx.restore();}else{ctx.fillStyle='#dce8df';ctx.textAlign='center';ctx.font='22px system-ui';ctx.fillText(status==='loading'?'Chargement et vérification des pixels…':status==='missing-atlas'?'Aucun atlas de combat validé':status==='missing-clip'?'Orientation manquante — aucun miroir':'Clip indisponible : chargement ou pixels invalides',480,270);}},[bank,sample,status]);
 const reset=()=>{setPlaying(false);setIndex(0);setMessage('');};
 const exportAtlas=()=>{if(!definition)return;try{const payload={schemaVersion:1,kind:'pit-reviewed-atlas-metadata',coverage,definition},url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='the-pit-'+fighterId+'-atlas.json';document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Métadonnées exportées ; aucun état de sauvegarde modifié.');}catch{setMessage('Export impossible dans ce navigateur.');}};
 return <main className={styles.root} data-pit-production-lab data-fighter={fighterId} data-clip={selectedId??''} data-facing={facing} data-render-status={status} data-frame-index={resolved?.resolved.frame.frameIndex??''} data-frame-duration-ticks={clip?getPitLabFrameTicks(fighterId,clip,currentIndex):''}>
  <header className={styles.header}><div><p className={styles.eyebrow}>THE PIT · REGISTRE DE COMBAT RÉEL</p><h1>Atelier d’animation</h1><p>{PIT_LAB_FIGHTER_IDS.length} combattants sélectionnables. Les dessins et leurs orientations sont lus dans le registre utilisé par les combats.</p></div><Link href="/" className={styles.back}>Retour au jeu</Link></header>
  <p className={styles.notice}>Un clip correspond parfois à une seule phase d’attaque, pas à une animation complète. Une orientation manquante reste vide ; aucun rig ou miroir ne la remplace.</p>
  <div className={styles.layout}><section className={styles.viewer} aria-label="Inspection des sprites de combat"><canvas className={styles.canvas} ref={canvasRef} width={960} height={540} aria-label={PIT_FIGHTERS[fighterId].name+' · '+(selectedId??'atlas absent')+' · '+facing}/><div className={styles.readout}><strong>{PIT_FIGHTERS[fighterId].name}</strong><span>{selectedId??'Aucun clip'}</span><span>{facing==='right'?'Droite':'Gauche'} · dessin {clip?currentIndex+1:0}/{clip?.frames.length??0}</span></div><p className={styles.status} role="status">{status==='ready'?'Dessin validé chargé · rectangle et pivot du registre.':status==='loading'?'Vérification des images…':status==='missing-atlas'?'Aucun atlas validé pour ce combattant.':status==='missing-clip'?'Clip absent dans cette orientation. Aucun miroir appliqué.':'Image absente ou invalide : aucune animation affichée.'}</p><div className={styles.timeline}><label htmlFor="production-frame">Dessin courant</label><input id="production-frame" type="range" min={0} max={Math.max(0,(clip?.frames.length??1)-1)} value={currentIndex} disabled={!clip} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}}/><div className={styles.buttons}><button onClick={()=>{setPlaying(false);setIndex(0);}} disabled={!clip}>Début</button><button onClick={()=>{setPlaying(false);setIndex(n=>Math.max(0,n-1));}} disabled={!clip||currentIndex===0}>−1 dessin</button><button onClick={()=>setPlaying(v=>!v)} disabled={status!=='ready'} aria-pressed={playing}>{playing?'Pause':'Lecture'}</button><button onClick={()=>{setPlaying(false);setIndex(n=>n+1);}} disabled={!clip||currentIndex>=clip.frames.length-1}>+1 dessin</button></div></div></section>
  <aside className={styles.controls} aria-label="Réglages de production"><label htmlFor="production-fighter">Combattant</label><select id="production-fighter" value={fighterId} onChange={e=>{reset();setFighterId(e.target.value as PitFighterId);setAtlasId('');setClipId('idle');}}>{PIT_LAB_FIGHTER_IDS.map(id=><option key={id} value={id}>{PIT_FIGHTERS[id].name}</option>)}</select><label htmlFor="production-atlas">Atlas validé</label><select id="production-atlas" value={definition?.atlas.id??''} disabled={!definition} onChange={e=>{reset();setAtlasId(e.target.value);setClipId('idle');}}>{definitions.length?definitions.map(d=><option key={d.atlas.id} value={d.atlas.id}>{d.atlas.id}</option>):<option value="">Aucun atlas validé</option>}</select><label htmlFor="production-clip">Clip / phase</label><select id="production-clip" value={selectedId??''} disabled={!definition} onChange={e=>{reset();setClipId(e.target.value);}}>{clipIds.length?clipIds.map(id=><option key={id} value={id}>{id}</option>):<option value="">Aucun clip</option>}</select><label htmlFor="production-facing">Orientation</label><select id="production-facing" value={facing} onChange={e=>{reset();setFacing(e.target.value as 'left'|'right');}}><option value="right">Vers la droite</option><option value="left">Vers la gauche</option></select><label htmlFor="production-speed">Vitesse</label><select id="production-speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.25}>×0,25</option><option value={.5}>×0,5</option><option value={1}>×1</option></select><p data-pit-lab-coverage>{coverage.atlasCount} atlas · {coverage.sourcePages} sources · {coverage.clips} clips orientés · {coverage.drawings} dessins référencés. Droite : {coverage.rightClips} clips ; gauche : {coverage.leftClips} clips.</p><p>Chargés après vérification : {bank?.readyClipCount??0} clips. Les échecs de chargement ne sont pas comptés comme disponibles.</p><div className={styles.buttons}><button disabled={!definition} onClick={exportAtlas}>Exporter l’atlas JSON</button></div>{message?<p role="status">{message}</p>:null}</aside></div>
  <section className={styles.notice} style={{marginTop:24}} aria-label="Archives de production"><div className={styles.buttons}><a className={styles.back} href="/game/assets/v34/production-review/index.html">Atelier OpenAI V34 · décors, chasseurs et véhicules</a><button type="button" onClick={()=>setShowLegacy(v=>!v)} aria-expanded={showLegacy}>{showLegacy?'Fermer':'Ouvrir'} l’archive des rigs V3</button></div><p>Les rigs V3 sont des essais provisoires limités à Jungle/Berserker ; ils ne décrivent pas la couverture du combat actuel.</p></section>{showLegacy?<LegacyPitAnimationLab/>:null}
 </main>;
}
