import type {
  ArmorDefinition,
  ArmorId,
  CodexEntryId,
  DifficultyDefinition,
  DifficultyId,
  GearDefinition,
  GearId,
  MissionDefinition,
  MissionId,
  WeaponDefinition,
  WeaponId,
} from "./types";

// ---------------------------------------------------------------------------
// Armory
// ---------------------------------------------------------------------------

export const WEAPONS: readonly WeaponDefinition[] = [
  {
    id: "wristblades",
    name: "Lames de poignet",
    shortName: "Wristblades",
    description:
      "Lames rétractables intégrées. Le choix le plus direct et le plus honorable pour conclure une chasse.",
    attackType: "melee",
    role: "Combo rapide et parade rapprochée",
    weight: 0,
    honorPower: 1,
    damage: 22,
    heavyDamage: 50,
    cooldownMs: 260,
    rangePx: 74,
    projectileSpeedPx: 0,
    staminaCost: 8,
    energyCost: 0,
    ammo: null,
    color: "#d7f7eb",
    unlock: { minimumHonor: 0, requiredMissionId: null },
    upgradeCosts: [200, 450],
  },
  {
    id: "combistick",
    name: "Combistick",
    shortName: "Combistick",
    description:
      "Lance télescopique efficace en mêlée ou au lancer. Une arme rituelle précise qui doit être récupérée.",
    attackType: "hybrid",
    role: "Portée moyenne, contrôle et lancer puissant",
    weight: 2,
    honorPower: 1,
    damage: 30,
    heavyDamage: 68,
    cooldownMs: 430,
    rangePx: 550,
    projectileSpeedPx: 760,
    staminaCost: 12,
    energyCost: 0,
    ammo: 1,
    color: "#a8d3c5",
    unlock: { minimumHonor: 0, requiredMissionId: null },
    upgradeCosts: [200, 450],
  },
  {
    id: "plasma-caster",
    name: "Plasmacaster",
    shortName: "Plasma",
    description:
      "Canon d'épaule lié au biomask. Dévastateur, mais gourmand en énergie et peu honorable contre une proie faible.",
    attackType: "ranged",
    role: "Dégâts énergétiques et tir chargé",
    weight: 3,
    honorPower: 3,
    damage: 34,
    heavyDamage: 95,
    cooldownMs: 650,
    rangePx: 820,
    projectileSpeedPx: 900,
    staminaCost: 0,
    energyCost: 22,
    ammo: null,
    color: "#ff4f4f",
    unlock: { minimumHonor: 0, requiredMissionId: null },
    upgradeCosts: [200, 450],
  },
  {
    id: "yautja-bow",
    name: "Arc Yautja",
    shortName: "Arc",
    description:
      "Arc compact et silencieux. Les flèches peuvent être récupérées et gagnent en puissance avec la charge.",
    attackType: "ranged",
    role: "Précision silencieuse et dégâts de charge",
    weight: 2,
    honorPower: 2,
    damage: 20,
    heavyDamage: 65,
    cooldownMs: 520,
    rangePx: 920,
    projectileSpeedPx: 980,
    staminaCost: 4,
    energyCost: 0,
    ammo: 8,
    color: "#d4b76e",
    unlock: { minimumHonor: 300, requiredMissionId: "jungle-vey" },
    upgradeCosts: [200, 450],
  },
  {
    id: "smart-disc",
    name: "Smart Disc",
    shortName: "Disque",
    description:
      "Disque guidé pouvant traverser plusieurs cibles avant de revenir au chasseur.",
    attackType: "hybrid",
    role: "Ricochet, pénétration et retour automatique",
    weight: 2,
    honorPower: 2,
    damage: 70,
    heavyDamage: 45,
    cooldownMs: 7_000,
    rangePx: 760,
    projectileSpeedPx: 820,
    staminaCost: 0,
    energyCost: 20,
    ammo: 1,
    color: "#bde9ff",
    unlock: { minimumHonor: 800, requiredMissionId: "ice-cryostalker" },
    upgradeCosts: [200, 450],
  },
];

export const GEAR: readonly GearDefinition[] = [
  {
    id: "motion-sensor",
    name: "Capteur de mouvement",
    description:
      "Révèle brièvement les déplacements dans une large zone, même derrière les plateformes.",
    role: "Reconnaissance",
    weight: 1,
    charges: 3,
    durationSeconds: 12,
    rangePx: 500,
    color: "#61f2d2",
    unlock: { minimumHonor: 0, requiredMissionId: null },
    upgradeCosts: [150, 350],
  },
  {
    id: "audio-decoy",
    name: "Leurre audio",
    description:
      "Reproduit des vocalises et des signatures d'armes pour détourner une patrouille.",
    role: "Distraction",
    weight: 1,
    charges: 3,
    durationSeconds: 8,
    rangePx: 460,
    color: "#dccb65",
    unlock: { minimumHonor: 0, requiredMissionId: null },
    upgradeCosts: [150, 350],
  },
  {
    id: "netgun",
    name: "Netgun",
    description:
      "Immobilise une proie et crée une ouverture pour une mise à mort rapprochée.",
    role: "Contrôle d'une cible",
    weight: 1,
    charges: 4,
    durationSeconds: 4,
    rangePx: 430,
    color: "#d7e8df",
    unlock: { minimumHonor: 300, requiredMissionId: "jungle-vey" },
    upgradeCosts: [150, 350],
  },
  {
    id: "snare",
    name: "Piège de chasse",
    description:
      "Piège compact qui retient une proie ou ralentit fortement un adversaire Apex.",
    role: "Embuscade",
    weight: 1,
    charges: 2,
    durationSeconds: 5,
    rangePx: 86,
    color: "#f09d4f",
    unlock: { minimumHonor: 800, requiredMissionId: "ice-cryostalker" },
    upgradeCosts: [150, 350],
  },
];

export const ARMORS: readonly ArmorDefinition[] = [
  {
    id: "hunter",
    name: "Armure Hunter",
    description:
      "Équilibre traditionnel entre résistance, mobilité, énergie et capacité d'emport.",
    maxHealth: 160,
    maxStamina: 100,
    maxEnergy: 100,
    moveSpeedMultiplier: 1,
    energyRegenMultiplier: 1,
    meleeDamageMultiplier: 1,
    carryingCapacity: 8,
    medicompCharges: 2,
    color: "#8b6f4f",
    unlock: { minimumHonor: 0, requiredMissionId: null },
    upgradeCosts: [250, 550],
  },
  {
    id: "scout",
    name: "Armure Scout",
    description:
      "Armure légère pour les longues approches camouflées et les attaques depuis la hauteur.",
    maxHealth: 125,
    maxStamina: 115,
    maxEnergy: 110,
    moveSpeedMultiplier: 1.15,
    energyRegenMultiplier: 1.2,
    meleeDamageMultiplier: 0.95,
    carryingCapacity: 6,
    medicompCharges: 2,
    color: "#617c63",
    unlock: { minimumHonor: 300, requiredMissionId: "jungle-vey" },
    upgradeCosts: [250, 550],
  },
  {
    id: "berserker",
    name: "Armure Berserker",
    description:
      "Plaques lourdes et puissance de mêlée accrue, au prix de la vitesse et de la recharge énergétique.",
    maxHealth: 220,
    maxStamina: 90,
    maxEnergy: 90,
    moveSpeedMultiplier: 0.86,
    energyRegenMultiplier: 0.85,
    meleeDamageMultiplier: 1.15,
    carryingCapacity: 10,
    medicompCharges: 2,
    color: "#7e4640",
    unlock: { minimumHonor: 800, requiredMissionId: "ice-cryostalker" },
    upgradeCosts: [250, 550],
  },
];

export const DIFFICULTIES: readonly DifficultyDefinition[] = [
  {
    id: "young-blood",
    name: "Young Blood",
    description:
      "Indices de traque généreux et deux checkpoints pour apprendre les outils du chasseur.",
    enemyHealthMultiplier: 0.9,
    enemyDamageMultiplier: 0.75,
    detectionMultiplier: 0.85,
    rewardMultiplier: 1,
    checkpointCount: 2,
    medicompModifier: 1,
    unlockedByDefault: true,
  },
  {
    id: "hunter",
    name: "Hunter",
    description:
      "L'expérience équilibrée : une proie dangereuse, un checkpoint avant l'Apex.",
    enemyHealthMultiplier: 1,
    enemyDamageMultiplier: 1,
    detectionMultiplier: 1,
    rewardMultiplier: 1.15,
    checkpointCount: 1,
    medicompModifier: 1,
    unlockedByDefault: true,
  },
  {
    id: "elite",
    name: "Elite",
    description:
      "Les proies réagissent plus vite, encaissent davantage et ne laissent aucun checkpoint.",
    enemyHealthMultiplier: 1.15,
    enemyDamageMultiplier: 1.25,
    detectionMultiplier: 1.25,
    rewardMultiplier: 1.35,
    checkpointCount: 0,
    medicompModifier: 1,
    unlockedByDefault: true,
  },
  {
    id: "elder",
    name: "Elder",
    description:
      "Rite d'après-campagne : ennemis renforcés, un seul Medicomp et aucune reprise.",
    enemyHealthMultiplier: 1.25,
    enemyDamageMultiplier: 1.5,
    detectionMultiplier: 1.35,
    rewardMultiplier: 1.6,
    checkpointCount: 0,
    medicompModifier: -1,
    unlockedByDefault: false,
  },
];

// ---------------------------------------------------------------------------
// Three complete campaign hunts
// ---------------------------------------------------------------------------

export const MISSIONS: readonly MissionDefinition[] = [
  {
    id: "jungle-vey",
    order: 1,
    title: "Sang dans la canopée",
    subtitle: "La commandante qui a appris à voir l'invisible",
    planetName: "Oseris-IV",
    biome: "jungle",
    targetName: "Commandante Vey",
    targetKind: "human",
    briefing:
      "Une unité armée a récupéré un transpondeur Yautja et l'utilise pour tendre des embuscades. Étudie ses éclaireurs, reprends la technologie du clan et affronte leur commandante, une guerrière qui a survécu à deux chasses.",
    threatLevel: 3,
    prerequisiteMissionId: null,
    recommendedArmorId: "hunter",
    recommendedWeaponIds: ["combistick", "plasma-caster"],
    parTimeSeconds: 600,
    baseRewards: { honor: 100, clanMarks: 180 },
    palette: {
      sky: "#071a18",
      haze: "#174b3a",
      ground: "#10251d",
      platform: "#315139",
      accent: "#6bff9c",
      danger: "#ff5a47",
    },
    objectives: [
      {
        id: "scan-vanguard",
        label: "Étudier l'avant-garde",
        description:
          "Scanne trois soldats pour identifier les contre-mesures thermiques de Vey.",
        kind: "scan",
        required: true,
        targetCount: 3,
        honorBonus: 15,
      },
      {
        id: "recover-transponder",
        label: "Reprendre le transpondeur",
        description:
          "Récupère intacte la technologie Yautja dans le camp avancé.",
        kind: "recover",
        required: true,
        targetCount: 1,
        honorBonus: 25,
      },
      {
        id: "defeat-vey",
        label: "Affronter la commandante Vey",
        description:
          "Force Vey à épuiser ses fusées et réclame une victoire digne.",
        kind: "boss",
        required: true,
        targetCount: 1,
        honorBonus: 40,
      },
      {
        id: "extract-jungle-trophy",
        label: "Quitter la zone de chasse",
        description:
          "Rejoins le point d'extraction avec le trophée et le transpondeur.",
        kind: "extract",
        required: true,
        targetCount: 1,
        honorBonus: 10,
      },
    ],
    honorRules: [
      {
        id: "study-vey",
        label: "Connaître sa proie",
        description: "Scanne Vey avant de lui porter le premier coup.",
        kind: "scan-target",
        bonus: 15,
        violationPenalty: 0,
      },
      {
        id: "protect-tech",
        label: "Ne laisser aucune technologie",
        description: "Le transpondeur doit revenir au clan.",
        kind: "recover-technology",
        bonus: 20,
        violationPenalty: 25,
      },
      {
        id: "restrained-caster",
        label: "Puissance mesurée",
        description:
          "N'utilise pas de tir plasma chargé contre les soldats ordinaires.",
        kind: "weapon-restraint",
        bonus: 15,
        violationPenalty: 10,
      },
    ],
    enemyWaves: [
      {
        id: "jungle-patrol",
        trigger: "start",
        triggerId: null,
        archetype: "rifle-soldier",
        count: 4,
        health: 55,
        damage: 8,
        moveSpeed: 125,
        threatLevel: 1,
        spawnDelaySeconds: 0,
      },
      {
        id: "jungle-scouts",
        trigger: "objective",
        triggerId: "scan-vanguard",
        archetype: "scout",
        count: 3,
        health: 45,
        damage: 7,
        moveSpeed: 175,
        threatLevel: 1,
        spawnDelaySeconds: 1,
      },
      {
        id: "vey-guard",
        trigger: "objective",
        triggerId: "recover-transponder",
        archetype: "heavy",
        count: 2,
        health: 150,
        damage: 14,
        moveSpeed: 90,
        threatLevel: 3,
        spawnDelaySeconds: 1.5,
      },
    ],
    boss: {
      name: "Commandante Vey",
      title: "La proie qui voit l'invisible",
      maxHealth: 600,
      moveSpeed: 145,
      threatLevel: 4,
      color: "#df6c4f",
      silhouette: "human",
      trophyWindowSeconds: 12,
      attacks: [
        {
          id: "vey-rifle-burst",
          label: "Rafale disciplinée",
          damage: 10,
          cooldownSeconds: 2.2,
          rangePx: 640,
          telegraphMs: 520,
          behavior: "burst",
        },
        {
          id: "vey-flare",
          label: "Fusée révélatrice",
          damage: 5,
          cooldownSeconds: 7,
          rangePx: 390,
          telegraphMs: 900,
          behavior: "area",
        },
        {
          id: "vey-knife",
          label: "Contre rapproché",
          damage: 22,
          cooldownSeconds: 1.6,
          rangePx: 82,
          telegraphMs: 280,
          behavior: "melee",
        },
      ],
      phases: [
        {
          id: "vey-hunt",
          label: "Contre-chasse",
          startsAtHealthRatio: 1,
          behavior:
            "Vey alterne couverture et rafales, puis se couvre de boue lorsqu'elle perd la ligne de vue.",
          hazard: "Les fusées révèlent le camouflage dans leur halo.",
          speedMultiplier: 1,
          damageMultiplier: 1,
        },
        {
          id: "vey-reinforcements",
          label: "Dernier carré",
          startsAtHealthRatio: 0.65,
          behavior:
            "Vey appelle deux gardes et avance derrière des tirs de suppression.",
          hazard: "Les plateformes basses sont balayées par les rafales.",
          speedMultiplier: 1.08,
          damageMultiplier: 1.1,
        },
        {
          id: "vey-duel",
          label: "Guerrière acculée",
          startsAtHealthRatio: 0.3,
          behavior:
            "À court de munitions, Vey accepte le combat rapproché et expose ses défenses après chaque charge.",
          hazard: "Rompre le duel avec un tir lourd réduit l'honneur.",
          speedMultiplier: 1.18,
          damageMultiplier: 1.2,
        },
      ],
    },
    trophy: {
      id: "trophy-vey",
      name: "Insigne de Vey",
      description:
        "La marque d'une humaine ayant transformé une embuscade en véritable chasse.",
      targetName: "Commandante Vey",
      partId: "insignia",
      icon: "insignia",
    },
    codexUnlockIds: [
      "yautja-honor",
      "biomask",
      "cloaking-device",
      "osiris-jungle",
      "commandante-vey",
    ],
  },
  {
    id: "ice-cryostalker",
    order: 2,
    title: "Chaleur sous la glace",
    subtitle: "Le Cryostalker ne laisse aucune trace chaude",
    planetName: "Nivalis-K",
    biome: "ice",
    targetName: "Cryostalker Alpha",
    targetKind: "beast",
    briefing:
      "Une colonie d'extraction a réveillé une forme de vie Apex sous la banquise. Sa température imite la glace. Analyse ses traces bioélectriques, élimine sa meute et attire l'Alpha hors de ses tunnels.",
    threatLevel: 4,
    prerequisiteMissionId: "jungle-vey",
    recommendedArmorId: "scout",
    recommendedWeaponIds: ["yautja-bow", "combistick"],
    parTimeSeconds: 720,
    baseRewards: { honor: 140, clanMarks: 230 },
    palette: {
      sky: "#071729",
      haze: "#2d6180",
      ground: "#102839",
      platform: "#7898aa",
      accent: "#8cf5ff",
      danger: "#f55d77",
    },
    objectives: [
      {
        id: "scan-ice-traces",
        label: "Lire les traces bioélectriques",
        description:
          "Scanne trois empreintes froides pour calibrer le biomask.",
        kind: "scan",
        required: true,
        targetCount: 3,
        honorBonus: 20,
      },
      {
        id: "hunt-cryorunners",
        label: "Disperser la meute",
        description:
          "Élimine quatre Cryorunners avant qu'ils ne préviennent l'Alpha.",
        kind: "hunt",
        required: true,
        targetCount: 4,
        honorBonus: 20,
      },
      {
        id: "defeat-cryostalker",
        label: "Abattre l'Alpha",
        description:
          "Brise ses plaques en utilisant les piliers de glace, puis frappe les tissus exposés.",
        kind: "boss",
        required: true,
        targetCount: 1,
        honorBonus: 50,
      },
      {
        id: "extract-ice-trophy",
        label: "Extraire le trophée",
        description:
          "Rejoins la balise avant l'effondrement complet de la caverne.",
        kind: "extract",
        required: true,
        targetCount: 1,
        honorBonus: 10,
      },
    ],
    honorRules: [
      {
        id: "study-alpha",
        label: "Comprendre l'Apex",
        description: "Complète les trois scans avant d'attaquer l'Alpha.",
        kind: "scan-target",
        bonus: 20,
        violationPenalty: 0,
      },
      {
        id: "break-armor-cleanly",
        label: "Force contre instinct",
        description:
          "Brise au moins une plaque en attirant une charge contre un pilier.",
        kind: "weapon-restraint",
        bonus: 20,
        violationPenalty: 10,
      },
      {
        id: "no-second-wind-ice",
        label: "Chasseur inébranlable",
        description: "Termine sans déclencher le Second Wind.",
        kind: "no-second-wind",
        bonus: 15,
        violationPenalty: 0,
      },
    ],
    enemyWaves: [
      {
        id: "ice-runners",
        trigger: "start",
        triggerId: null,
        archetype: "cryostalker-runner",
        count: 4,
        health: 70,
        damage: 14,
        moveSpeed: 190,
        threatLevel: 2,
        spawnDelaySeconds: 0.8,
      },
      {
        id: "ice-salvagers",
        trigger: "objective",
        triggerId: "scan-ice-traces",
        archetype: "rifle-soldier",
        count: 3,
        health: 55,
        damage: 8,
        moveSpeed: 120,
        threatLevel: 1,
        spawnDelaySeconds: 1.2,
      },
      {
        id: "ice-brutes",
        trigger: "objective",
        triggerId: "hunt-cryorunners",
        archetype: "cryostalker-brute",
        count: 2,
        health: 180,
        damage: 22,
        moveSpeed: 118,
        threatLevel: 3,
        spawnDelaySeconds: 1,
      },
    ],
    boss: {
      name: "Cryostalker Alpha",
      title: "La faim sous la banquise",
      maxHealth: 720,
      moveSpeed: 175,
      threatLevel: 4,
      color: "#b9eafa",
      silhouette: "beast",
      trophyWindowSeconds: 14,
      attacks: [
        {
          id: "cryo-charge",
          label: "Charge blindée",
          damage: 30,
          cooldownSeconds: 4.8,
          rangePx: 610,
          telegraphMs: 950,
          behavior: "charge",
        },
        {
          id: "cryo-claws",
          label: "Balayage de griffes",
          damage: 24,
          cooldownSeconds: 1.8,
          rangePx: 110,
          telegraphMs: 360,
          behavior: "melee",
        },
        {
          id: "cryo-burrow",
          label: "Éruption sous-glaciaire",
          damage: 20,
          cooldownSeconds: 6.5,
          rangePx: 300,
          telegraphMs: 1_100,
          behavior: "area",
        },
      ],
      phases: [
        {
          id: "cryo-armored",
          label: "Carapace intacte",
          startsAtHealthRatio: 1,
          behavior:
            "L'Alpha charge en ligne droite. Les impacts contre les piliers fissurent son armure.",
          hazard: "Le sol signale tardivement les sorties de tunnel.",
          speedMultiplier: 1,
          damageMultiplier: 1,
        },
        {
          id: "cryo-pack",
          label: "Appel de la meute",
          startsAtHealthRatio: 0.55,
          behavior:
            "L'Alpha appelle des runners et alterne tunnel et attaques latérales.",
          hazard: "Deux Cryorunners rejoignent l'arène.",
          speedMultiplier: 1.12,
          damageMultiplier: 1.08,
        },
        {
          id: "cryo-exposed",
          label: "Prédateur blessé",
          startsAtHealthRatio: 0.22,
          behavior:
            "Sans carapace, l'Alpha devient plus rapide mais son dos bioélectrique reste exposé.",
          hazard: "Des stalactites tombent après chaque charge.",
          speedMultiplier: 1.25,
          damageMultiplier: 1.18,
        },
      ],
    },
    trophy: {
      id: "trophy-cryostalker",
      name: "Crâne de Cryostalker",
      description:
        "Carapace polaire d'un prédateur qui effaçait jusqu'à sa propre chaleur.",
      targetName: "Cryostalker Alpha",
      partId: "skull-and-spine",
      icon: "beast-skull",
    },
    codexUnlockIds: ["nivalis-ice", "cryostalker"],
  },
  {
    id: "volcano-bad-blood",
    order: 3,
    title: "Le dernier rite",
    subtitle: "Aucune chasse ne justifie la profanation du clan",
    planetName: "Cinder-12",
    biome: "volcano",
    targetName: "Le Bad Blood",
    targetKind: "yautja",
    briefing:
      "Trois chasseurs ont disparu autour d'un ancien sanctuaire. Un Paria utilise leurs trophées et leur technologie pour attirer de nouvelles victimes. Retrouve les marques des morts, détruis ses balises et impose le jugement du clan.",
    threatLevel: 4,
    prerequisiteMissionId: "ice-cryostalker",
    recommendedArmorId: "berserker",
    recommendedWeaponIds: ["smart-disc", "combistick"],
    parTimeSeconds: 840,
    baseRewards: { honor: 200, clanMarks: 320 },
    palette: {
      sky: "#17090c",
      haze: "#5d1f22",
      ground: "#1d1315",
      platform: "#493234",
      accent: "#ffb64b",
      danger: "#ff3c28",
    },
    objectives: [
      {
        id: "scan-fallen-hunters",
        label: "Honorer les chasseurs tombés",
        description:
          "Scanne les trois marques de clan avant de poursuivre le Paria.",
        kind: "scan",
        required: true,
        targetCount: 3,
        honorBonus: 30,
      },
      {
        id: "recover-stolen-beacons",
        label: "Détruire le piège",
        description:
          "Désactive trois balises volées sans les abandonner dans le sanctuaire.",
        kind: "recover",
        required: true,
        targetCount: 3,
        honorBonus: 30,
      },
      {
        id: "defeat-bad-blood",
        label: "Juger le Bad Blood",
        description:
          "Survis à ses armes de chasse, puis accepte son duel final.",
        kind: "boss",
        required: true,
        targetCount: 1,
        honorBonus: 60,
      },
      {
        id: "escape-self-destruct",
        label: "Empêcher l'effacement",
        description:
          "Interromps l'autodestruction en 45 secondes ou quitte la zone sans le trophée parfait.",
        kind: "extract",
        required: true,
        targetCount: 1,
        honorBonus: 25,
      },
    ],
    honorRules: [
      {
        id: "honor-fallen",
        label: "Mémoire du clan",
        description: "Trouve les trois marques des chasseurs assassinés.",
        kind: "recover-technology",
        bonus: 25,
        violationPenalty: 20,
      },
      {
        id: "accept-final-duel",
        label: "Le dernier rite",
        description:
          "Durant la phase de duel, utilise uniquement les Wristblades ou le Combistick.",
        kind: "accept-duel",
        bonus: 35,
        violationPenalty: 30,
      },
      {
        id: "stop-purge",
        label: "Ne laisser aucune trace",
        description:
          "Interromps l'autodestruction et récupère la technologie profanée.",
        kind: "recover-technology",
        bonus: 30,
        violationPenalty: 25,
      },
    ],
    enemyWaves: [
      {
        id: "volcano-hounds",
        trigger: "start",
        triggerId: null,
        archetype: "razor-hound",
        count: 5,
        health: 65,
        damage: 13,
        moveSpeed: 205,
        threatLevel: 1,
        spawnDelaySeconds: 0.6,
      },
      {
        id: "volcano-initiates",
        trigger: "objective",
        triggerId: "scan-fallen-hunters",
        archetype: "bad-blood-initiate",
        count: 3,
        health: 130,
        damage: 18,
        moveSpeed: 150,
        threatLevel: 3,
        spawnDelaySeconds: 1.5,
      },
      {
        id: "volcano-ambush",
        trigger: "objective",
        triggerId: "recover-stolen-beacons",
        archetype: "razor-hound",
        count: 4,
        health: 65,
        damage: 13,
        moveSpeed: 215,
        threatLevel: 1,
        spawnDelaySeconds: 0.5,
      },
    ],
    boss: {
      name: "Le Bad Blood",
      title: "Paria aux trophées volés",
      maxHealth: 850,
      moveSpeed: 178,
      threatLevel: 4,
      color: "#a83c2e",
      silhouette: "yautja",
      trophyWindowSeconds: 45,
      attacks: [
        {
          id: "pariah-disc",
          label: "Smart Disc volé",
          damage: 34,
          cooldownSeconds: 5.2,
          rangePx: 700,
          telegraphMs: 650,
          behavior: "disc",
        },
        {
          id: "pariah-plasma",
          label: "Tir plasma",
          damage: 38,
          cooldownSeconds: 4.2,
          rangePx: 760,
          telegraphMs: 900,
          behavior: "plasma",
        },
        {
          id: "pariah-combistick",
          label: "Combistick du Paria",
          damage: 28,
          cooldownSeconds: 1.45,
          rangePx: 122,
          telegraphMs: 310,
          behavior: "melee",
        },
        {
          id: "pariah-purge",
          label: "Surcharge du sanctuaire",
          damage: 45,
          cooldownSeconds: 8,
          rangePx: 340,
          telegraphMs: 1_200,
          behavior: "area",
        },
      ],
      phases: [
        {
          id: "pariah-stalk",
          label: "Chasseur de chasseurs",
          startsAtHealthRatio: 1,
          behavior:
            "Le Paria alterne camouflage, Smart Disc et tirs plasma depuis les hauteurs.",
          hazard: "La chaleur volcanique sature la vision thermique.",
          speedMultiplier: 1,
          damageMultiplier: 1,
        },
        {
          id: "pariah-duel",
          label: "Duel du sanctuaire",
          startsAtHealthRatio: 0.58,
          behavior:
            "Une impulsion coupe les armes énergétiques. Le Paria engage au Combistick et aux Wristblades.",
          hazard: "Employer une arme à distance disponible rompt le rite.",
          speedMultiplier: 1.16,
          damageMultiplier: 1.12,
        },
        {
          id: "pariah-self-destruct",
          label: "Effacement",
          startsAtHealthRatio: 0.18,
          behavior:
            "Le Paria lance une purge de 45 secondes. Trois consoles doivent être interrompues entre ses charges.",
          hazard:
            "L'explosion détruit le trophée et la technologie si le compte à rebours expire.",
          speedMultiplier: 1.25,
          damageMultiplier: 1.25,
        },
      ],
    },
    trophy: {
      id: "trophy-bad-blood",
      name: "Masque du Paria",
      description:
        "Un biomask récupéré après le jugement d'un chasseur ayant trahi le code.",
      targetName: "Le Bad Blood",
      partId: "mask",
      icon: "broken-mask",
    },
    codexUnlockIds: ["cinder-volcano", "bad-blood"],
  },
];

// ---------------------------------------------------------------------------
// Codex copy and indexed accessors for menus/runtime code
// ---------------------------------------------------------------------------

export interface CodexEntryDefinition {
  id: CodexEntryId;
  category: "tradition" | "technology" | "planet" | "prey";
  title: string;
  text: string;
}

export const CODEX_ENTRIES: readonly CodexEntryDefinition[] = [
  {
    id: "yautja-honor",
    category: "tradition",
    title: "Valeur de la proie",
    text: "Une proie observée, dangereuse et affrontée avec une force mesurée rapporte davantage d'honneur.",
  },
  {
    id: "biomask",
    category: "technology",
    title: "Biomask",
    text: "Le masque analyse chaleur, activité bioélectrique et technologie. Ses modes partagent l'énergie du chasseur.",
  },
  {
    id: "cloaking-device",
    category: "technology",
    title: "Camouflage actif",
    text: "Presque parfait à l'arrêt, le camouflage réfracte visiblement la lumière en mouvement et cède au moment d'attaquer.",
  },
  {
    id: "osiris-jungle",
    category: "planet",
    title: "Oseris-IV",
    text: "Une jungle humide où la canopée favorise l'approche verticale, mais où l'eau trahit les systèmes de camouflage.",
  },
  {
    id: "commandante-vey",
    category: "prey",
    title: "Commandante Vey",
    text: "Chef d'une unité de récupération, Vey emploie boue froide, fusées spectrales et tirs de suppression.",
  },
  {
    id: "nivalis-ice",
    category: "planet",
    title: "Nivalis-K",
    text: "Sous la raffinerie gelée, des galeries biologiques absorbent chaleur et vibrations.",
  },
  {
    id: "cryostalker",
    category: "prey",
    title: "Cryostalker",
    text: "Prédateur polaire original dont la carapace imite la glace. Une charge mal dirigée fracture ses plaques.",
  },
  {
    id: "cinder-volcano",
    category: "planet",
    title: "Cinder-12",
    text: "Sanctuaire volcanique abandonné. Le rayonnement thermique rend les signatures ordinaires presque inutiles.",
  },
  {
    id: "bad-blood",
    category: "prey",
    title: "Bad Blood",
    text: "Un Paria qui vole trophées et technologie. Le combattre est un jugement du clan, pas une chasse ordinaire.",
  },
];

function indexById<T extends { id: string }>(
  items: readonly T[],
): Record<string, T> {
  return Object.fromEntries(items.map((item) => [item.id, item]));
}

export const WEAPON_BY_ID = indexById(WEAPONS) as Record<
  WeaponId,
  WeaponDefinition
>;
export const GEAR_BY_ID = indexById(GEAR) as Record<GearId, GearDefinition>;
export const ARMOR_BY_ID = indexById(ARMORS) as Record<ArmorId, ArmorDefinition>;
export const DIFFICULTY_BY_ID = indexById(DIFFICULTIES) as Record<
  DifficultyId,
  DifficultyDefinition
>;
export const MISSION_BY_ID = indexById(MISSIONS) as Record<
  MissionId,
  MissionDefinition
>;
export const CODEX_ENTRY_BY_ID = indexById(CODEX_ENTRIES) as Record<
  CodexEntryId,
  CodexEntryDefinition
>;
