import type { MissionDefinition } from "./types";

export const ENEMY_V7_FRAME_LABELS = [
  "repos",
  "déplacement A",
  "déplacement B",
  "attaque",
  "impact",
  "mort",
] as const;

export const ENEMY_V7_CATEGORIES = [
  "fauna",
  "flora",
  "humanoid",
  "bad-blood",
  "other",
] as const;

export type EnemyV7Category = (typeof ENEMY_V7_CATEGORIES)[number];
export type EnemyV7RuntimeKind = "human" | "beast" | "yautja";

export interface EnemyV7Definition {
  id: string;
  name: string;
  category: EnemyV7Category;
  categoryLabel: string;
  runtimeKind: EnemyV7RuntimeKind;
  missionId: MissionDefinition["id"];
  role: string;
  behavior: string;
  trophy: string;
  threat: 1 | 2 | 3 | 4;
  width: number;
  height: number;
  animationFps: number;
  sheetPath: string;
  sourceUrls: readonly [string, string];
  provenance: "canon-remix" | "original-lore-extension";
}

const BADLANDS_SOURCE =
  "https://www.20thcenturystudios.com/movies/predator-badlands";
const PRESERVE_SOURCE =
  "https://www.avpcentral.com/predator-game-preserve-planet";
const PRIMAL_HUNT_SOURCE =
  "https://avpunknown.com/games/2000/avp2primalhunt";
const AVP_GAME_SOURCE =
  "https://store.steampowered.com/app/10680/Aliens_vs_Predator/";
const HUNTING_GROUNDS_SOURCE =
  "https://store.steampowered.com/app/1556200/Predator_Hunting_Grounds/";
const BAD_BLOOD_SOURCE =
  "https://www.avpgalaxy.net/literature/predator-comics/";

const sheet = (group: string, id: string) =>
  `/game/sprites/v7/enemies/${group}/${id}-sheet.png`;

export const ENEMY_V7_DEFINITIONS = [
  {
    id: "hell-hound-stalker",
    name: "Traqueur Hell-Hound",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "volcano-bad-blood",
    role: "Pisteur de meute",
    behavior: "Contourne, flaire les traces fraîches puis bondit en diagonale.",
    trophy: "Crâne canin à crête",
    threat: 2,
    width: 108,
    height: 78,
    animationFps: 9,
    sheetPath: sheet("fauna", "hell-hound-stalker"),
    sourceUrls: [PRESERVE_SOURCE, BADLANDS_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "river-ghost-brute",
    name: "Brute River Ghost",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "volcano-bad-blood",
    role: "Prédateur camouflé",
    behavior: "Reste immobile dans les particules chaudes avant une charge courte.",
    trophy: "Mandibule membraneuse",
    threat: 3,
    width: 84,
    height: 114,
    animationFps: 7,
    sheetPath: sheet("fauna", "river-ghost-brute"),
    sourceUrls: [PRESERVE_SOURCE, BADLANDS_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "kalisk-juvenile",
    name: "Kalisk juvénile",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "ice-cryostalker",
    role: "Apex régénératif",
    behavior: "Encaisse, se replie et revient par une seconde impulsion agressive.",
    trophy: "Plaque frontale régénérative",
    threat: 4,
    width: 142,
    height: 104,
    animationFps: 7,
    sheetPath: sheet("fauna", "kalisk-juvenile"),
    sourceUrls: [BADLANDS_SOURCE, PRESERVE_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "cryostalker-alpha",
    name: "Cryostalker alpha",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "ice-cryostalker",
    role: "Chasseur sous-glaciaire",
    behavior: "Poursuit les signatures thermiques et frappe depuis les congères.",
    trophy: "Plaque de gorge cryogène",
    threat: 3,
    width: 124,
    height: 92,
    animationFps: 9,
    sheetPath: sheet("fauna", "cryostalker-alpha"),
    sourceUrls: [PRIMAL_HUNT_SOURCE, BADLANDS_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "lv1201-winged-vermin",
    name: "Vermine ailée LV-1201",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "ice-cryostalker",
    role: "Harcèlement aérien",
    behavior: "Décrit un arc, plonge sur le masque puis regagne la hauteur.",
    trophy: "Carapace thoracique ailée",
    threat: 1,
    width: 98,
    height: 72,
    animationFps: 11,
    sheetPath: sheet("fauna", "lv1201-winged-vermin"),
    sourceUrls: [PRIMAL_HUNT_SOURCE, AVP_GAME_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "razorback-grazer",
    name: "Brouteur dos-rasoir",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "ice-cryostalker",
    role: "Herbivore territorial",
    behavior: "Avertit en raclant le sol puis charge si le chasseur insiste.",
    trophy: "Omoplate dentelée",
    threat: 2,
    width: 138,
    height: 88,
    animationFps: 6,
    sheetPath: sheet("fauna", "razorback-grazer"),
    sourceUrls: [PRESERVE_SOURCE, BADLANDS_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "amber-mire-lurker",
    name: "Rôdeur des tourbières d’ambre",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "ice-cryostalker",
    role: "Embuscade amphibie",
    behavior: "Rampe sous la surface puis projette sa mâchoire vers les jambes.",
    trophy: "Double mâchoire fossilisée",
    threat: 2,
    width: 116,
    height: 74,
    animationFps: 8,
    sheetPath: sheet("fauna", "amber-mire-lurker"),
    sourceUrls: [PRESERVE_SOURCE, PRIMAL_HUNT_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "bonecrest-ravager",
    name: "Ravageur à crête osseuse",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "ice-cryostalker",
    role: "Bélier de meute",
    behavior: "Protège les flancs de la meute et renverse au contact.",
    trophy: "Crête d’impact",
    threat: 3,
    width: 132,
    height: 96,
    animationFps: 7,
    sheetPath: sheet("fauna", "bonecrest-ravager"),
    sourceUrls: [BADLANDS_SOURCE, PRESERVE_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "canopy-razorwing",
    name: "Razorwing de canopée",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "jungle-vey",
    role: "Prédateur arboricole",
    behavior: "S’accroche aux hauteurs et lacère pendant un passage plané.",
    trophy: "Serre membraneuse",
    threat: 2,
    width: 112,
    height: 80,
    animationFps: 10,
    sheetPath: sheet("fauna", "canopy-razorwing"),
    sourceUrls: [PRESERVE_SOURCE, PRIMAL_HUNT_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "volcanic-ashmaw",
    name: "Gueule-cendre volcanique",
    category: "fauna",
    categoryLabel: "Faune",
    runtimeKind: "beast",
    missionId: "volcano-bad-blood",
    role: "Fouisseur ignifuge",
    behavior: "Émerge des retombées, mord puis disparaît dans la cendre.",
    trophy: "Crocs vitrifiés",
    threat: 2,
    width: 120,
    height: 82,
    animationFps: 8,
    sheetPath: sheet("fauna", "volcanic-ashmaw"),
    sourceUrls: [BADLANDS_SOURCE, PRESERVE_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "carnivore-vine",
    name: "Liane carnivore",
    category: "flora",
    categoryLabel: "Flore hostile",
    runtimeKind: "beast",
    missionId: "jungle-vey",
    role: "Entrave végétale",
    behavior: "Détecte les vibrations et fouette les cibles qui courent.",
    trophy: "Nœud sensoriel",
    threat: 2,
    width: 104,
    height: 110,
    animationFps: 7,
    sheetPath: sheet("flora-other", "carnivore-vine"),
    sourceUrls: [BADLANDS_SOURCE, PRIMAL_HUNT_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "spore-bloom",
    name: "Floraison à spores",
    category: "flora",
    categoryLabel: "Flore hostile",
    runtimeKind: "beast",
    missionId: "jungle-vey",
    role: "Contrôle de zone",
    behavior: "Gonfle sa corolle avant d’émettre un nuage qui révèle le camouflage.",
    trophy: "Sac pollinique intact",
    threat: 2,
    width: 100,
    height: 112,
    animationFps: 6,
    sheetPath: sheet("flora-other", "spore-bloom"),
    sourceUrls: [BADLANDS_SOURCE, PRESERVE_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "razor-reed",
    name: "Roseau rasoir",
    category: "flora",
    categoryLabel: "Flore hostile",
    runtimeKind: "beast",
    missionId: "volcano-bad-blood",
    role: "Barrière mobile",
    behavior: "Se penche dans le vent puis détend ses feuilles comme des lames.",
    trophy: "Rhizome tranchant",
    threat: 1,
    width: 88,
    height: 122,
    animationFps: 8,
    sheetPath: sheet("flora-other", "razor-reed"),
    sourceUrls: [BADLANDS_SOURCE, PRIMAL_HUNT_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "grapple-root",
    name: "Racine grappin",
    category: "flora",
    categoryLabel: "Flore hostile",
    runtimeKind: "beast",
    missionId: "volcano-bad-blood",
    role: "Prédateur souterrain",
    behavior: "Suit les pas sous terre et jaillit pour immobiliser une cheville.",
    trophy: "Bulbe contractile",
    threat: 2,
    width: 112,
    height: 84,
    animationFps: 8,
    sheetPath: sheet("flora-other", "grapple-root"),
    sourceUrls: [PRIMAL_HUNT_SOURCE, BADLANDS_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "acid-pitcher",
    name: "Urne acide",
    category: "flora",
    categoryLabel: "Flore hostile",
    runtimeKind: "beast",
    missionId: "volcano-bad-blood",
    role: "Artillerie organique",
    behavior: "Compresse sa poche et projette une salve corrosive en cloche.",
    trophy: "Poche catalytique",
    threat: 3,
    width: 96,
    height: 116,
    animationFps: 6,
    sheetPath: sheet("flora-other", "acid-pitcher"),
    sourceUrls: [BADLANDS_SOURCE, AVP_GAME_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "sentinel-orchid",
    name: "Orchidée sentinelle",
    category: "flora",
    categoryLabel: "Flore hostile",
    runtimeKind: "beast",
    missionId: "volcano-bad-blood",
    role: "Détection thermique",
    behavior: "Ouvre son iris bioluminescent et alerte tous les ennemis proches.",
    trophy: "Iris thermosensible",
    threat: 2,
    width: 92,
    height: 118,
    animationFps: 6,
    sheetPath: sheet("flora-other", "sentinel-orchid"),
    sourceUrls: [BADLANDS_SOURCE, PRESERVE_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "colonial-marine",
    name: "Marine colonial",
    category: "humanoid",
    categoryLabel: "Humanoïde",
    runtimeKind: "human",
    missionId: "jungle-vey",
    role: "Fusilier polyvalent",
    behavior: "Progresse en binôme, couvre les angles et tire par courtes rafales.",
    trophy: "Plaque d’unité",
    threat: 2,
    width: 66,
    height: 96,
    animationFps: 9,
    sheetPath: sheet("humanoid-badblood", "colonial-marine"),
    sourceUrls: [AVP_GAME_SOURCE, HUNTING_GROUNDS_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "owlf-commando",
    name: "Commando OWLF",
    category: "humanoid",
    categoryLabel: "Humanoïde",
    runtimeKind: "human",
    missionId: "jungle-vey",
    role: "Contre-chasseur",
    behavior: "Utilise brouillage thermique, grenades de marquage et tirs coordonnés.",
    trophy: "Viseur anti-camouflage",
    threat: 3,
    width: 68,
    height: 98,
    animationFps: 9,
    sheetPath: sheet("humanoid-badblood", "owlf-commando"),
    sourceUrls: [HUNTING_GROUNDS_SOURCE, AVP_GAME_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "colonial-sniper",
    name: "Tireuse coloniale",
    category: "humanoid",
    categoryLabel: "Humanoïde",
    runtimeKind: "human",
    missionId: "jungle-vey",
    role: "Tir longue portée",
    behavior: "Cherche une ligne claire et télégraphie un tir perforant précis.",
    trophy: "Optique balistique",
    threat: 3,
    width: 66,
    height: 96,
    animationFps: 8,
    sheetPath: sheet("humanoid-badblood", "colonial-sniper"),
    sourceUrls: [AVP_GAME_SOURCE, HUNTING_GROUNDS_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "frontier-raider",
    name: "Pillard de frontière",
    category: "humanoid",
    categoryLabel: "Humanoïde",
    runtimeKind: "human",
    missionId: "jungle-vey",
    role: "Escarmouche improvisée",
    behavior: "Feinte la fuite, place un piège sonore puis revient au contact.",
    trophy: "Masque de raid",
    threat: 1,
    width: 66,
    height: 94,
    animationFps: 10,
    sheetPath: sheet("humanoid-badblood", "frontier-raider"),
    sourceUrls: [HUNTING_GROUNDS_SOURCE, AVP_GAME_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "corporate-heavy",
    name: "Lourd corporatiste",
    category: "humanoid",
    categoryLabel: "Humanoïde",
    runtimeKind: "human",
    missionId: "jungle-vey",
    role: "Suppression blindée",
    behavior: "Ancre son arme lourde et force le chasseur à changer de hauteur.",
    trophy: "Noyau de servomoteur",
    threat: 3,
    width: 76,
    height: 102,
    animationFps: 7,
    sheetPath: sheet("humanoid-badblood", "corporate-heavy"),
    sourceUrls: [AVP_GAME_SOURCE, HUNTING_GROUNDS_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "bad-blood-duelist",
    name: "Bad Blood duelliste",
    category: "bad-blood",
    categoryLabel: "Bad Blood",
    runtimeKind: "yautja",
    missionId: "volcano-bad-blood",
    role: "Briseur de code",
    behavior: "Provoque un duel puis rompt volontairement la distance d’honneur.",
    trophy: "Biomask fendu",
    threat: 3,
    width: 76,
    height: 114,
    animationFps: 9,
    sheetPath: sheet("humanoid-badblood", "bad-blood-duelist"),
    sourceUrls: [BAD_BLOOD_SOURCE, HUNTING_GROUNDS_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "bad-blood-plasma-gunner",
    name: "Bad Blood artilleur plasma",
    category: "bad-blood",
    categoryLabel: "Bad Blood",
    runtimeKind: "yautja",
    missionId: "volcano-bad-blood",
    role: "Surcharge à distance",
    behavior: "Sature une plateforme de plasma sans respecter la valeur de la proie.",
    trophy: "Canon dorsal profané",
    threat: 4,
    width: 82,
    height: 116,
    animationFps: 8,
    sheetPath: sheet("humanoid-badblood", "bad-blood-plasma-gunner"),
    sourceUrls: [BAD_BLOOD_SOURCE, HUNTING_GROUNDS_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "bad-blood-netmaster",
    name: "Bad Blood maître-filet",
    category: "bad-blood",
    categoryLabel: "Bad Blood",
    runtimeKind: "yautja",
    missionId: "volcano-bad-blood",
    role: "Capture cruelle",
    behavior: "Immobilise puis attaque avant que la proie puisse se libérer.",
    trophy: "Projecteur de filet dentelé",
    threat: 3,
    width: 78,
    height: 112,
    animationFps: 9,
    sheetPath: sheet("humanoid-badblood", "bad-blood-netmaster"),
    sourceUrls: [BAD_BLOOD_SOURCE, HUNTING_GROUNDS_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "bad-blood-cloaked-stalker",
    name: "Bad Blood traqueur occulté",
    category: "bad-blood",
    categoryLabel: "Bad Blood",
    runtimeKind: "yautja",
    missionId: "volcano-bad-blood",
    role: "Assassin camouflé",
    behavior: "Maintient sa cape au contact et frappe depuis l’angle mort.",
    trophy: "Générateur de cape instable",
    threat: 4,
    width: 76,
    height: 114,
    animationFps: 10,
    sheetPath: sheet("humanoid-badblood", "bad-blood-cloaked-stalker"),
    sourceUrls: [BAD_BLOOD_SOURCE, HUNTING_GROUNDS_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "bad-blood-trophy-butcher",
    name: "Bad Blood boucher de trophées",
    category: "bad-blood",
    categoryLabel: "Bad Blood",
    runtimeKind: "yautja",
    missionId: "volcano-bad-blood",
    role: "Prédateur sacrilège",
    behavior: "Porte des prises volées comme blindage et utilise une lame lourde.",
    trophy: "Collier de prises volées",
    threat: 4,
    width: 86,
    height: 118,
    animationFps: 7,
    sheetPath: sheet("humanoid-badblood", "bad-blood-trophy-butcher"),
    sourceUrls: [BAD_BLOOD_SOURCE, HUNTING_GROUNDS_SOURCE],
    provenance: "original-lore-extension",
  },
  {
    id: "xeno-drone",
    name: "Drone xénomorphe",
    category: "other",
    categoryLabel: "Autre menace",
    runtimeKind: "beast",
    missionId: "ice-cryostalker",
    role: "Prédateur de couloir",
    behavior: "Accélère à quatre appuis et cherche le plafond avant de bondir.",
    trophy: "Dôme crânien",
    threat: 3,
    width: 82,
    height: 108,
    animationFps: 11,
    sheetPath: sheet("flora-other", "xeno-drone"),
    sourceUrls: [AVP_GAME_SOURCE, PRIMAL_HUNT_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "xeno-praetorian",
    name: "Prétorien xénomorphe",
    category: "other",
    categoryLabel: "Autre menace",
    runtimeKind: "beast",
    missionId: "ice-cryostalker",
    role: "Garde de ruche",
    behavior: "Protège les plus faibles, bloque de face et balaie avec sa queue.",
    trophy: "Couronne chitineuse",
    threat: 4,
    width: 112,
    height: 126,
    animationFps: 8,
    sheetPath: sheet("flora-other", "xeno-praetorian"),
    sourceUrls: [AVP_GAME_SOURCE, PRIMAL_HUNT_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "weyland-synth",
    name: "Synthétique corporatif",
    category: "other",
    categoryLabel: "Autre menace",
    runtimeKind: "human",
    missionId: "jungle-vey",
    role: "Unité de récupération",
    behavior: "Ignore la douleur, verrouille la technologie et combat jusqu’à rupture.",
    trophy: "Noyau mnésique",
    threat: 3,
    width: 68,
    height: 98,
    animationFps: 8,
    sheetPath: sheet("flora-other", "weyland-synth"),
    sourceUrls: [AVP_GAME_SOURCE, HUNTING_GROUNDS_SOURCE],
    provenance: "canon-remix",
  },
  {
    id: "ancient-guardian",
    name: "Gardien ancien",
    category: "other",
    categoryLabel: "Autre menace",
    runtimeKind: "human",
    missionId: "ice-cryostalker",
    role: "Automate de sanctuaire",
    behavior: "S’éveille à proximité des reliques et alterne rayon et frappe de bouclier.",
    trophy: "Cœur de glyphes",
    threat: 4,
    width: 86,
    height: 116,
    animationFps: 7,
    sheetPath: sheet("flora-other", "ancient-guardian"),
    sourceUrls: [AVP_GAME_SOURCE, PRIMAL_HUNT_SOURCE],
    provenance: "original-lore-extension",
  },
] as const satisfies readonly EnemyV7Definition[];

export type EnemyV7Id = (typeof ENEMY_V7_DEFINITIONS)[number]["id"];

export const ENEMY_V7_BY_ID = Object.fromEntries(
  ENEMY_V7_DEFINITIONS.map((enemy) => [enemy.id, enemy]),
) as Record<EnemyV7Id, (typeof ENEMY_V7_DEFINITIONS)[number]>;

/** Each of the 30 regular spawn slots receives one unique V7 enemy. */
export const ENEMY_V7_IDS_BY_WAVE = {
  "jungle-patrol": [
    "colonial-marine",
    "owlf-commando",
    "frontier-raider",
    "corporate-heavy",
  ],
  "jungle-scouts": ["canopy-razorwing", "carnivore-vine", "spore-bloom"],
  "vey-guard": ["colonial-sniper", "weyland-synth"],
  "ice-runners": [
    "cryostalker-alpha",
    "lv1201-winged-vermin",
    "amber-mire-lurker",
    "bonecrest-ravager",
  ],
  "ice-salvagers": ["ancient-guardian", "xeno-drone", "xeno-praetorian"],
  "ice-brutes": ["razorback-grazer", "kalisk-juvenile"],
  "volcano-hounds": [
    "hell-hound-stalker",
    "river-ghost-brute",
    "volcanic-ashmaw",
    "razor-reed",
    "grapple-root",
  ],
  "volcano-initiates": [
    "bad-blood-duelist",
    "bad-blood-plasma-gunner",
    "bad-blood-netmaster",
  ],
  "volcano-ambush": [
    "acid-pitcher",
    "sentinel-orchid",
    "bad-blood-cloaked-stalker",
    "bad-blood-trophy-butcher",
  ],
} as const satisfies Record<string, readonly EnemyV7Id[]>;

export type EnemyV7WaveId = keyof typeof ENEMY_V7_IDS_BY_WAVE;

export function enemyV7ForWave(
  waveId: string,
  index: number,
): (typeof ENEMY_V7_DEFINITIONS)[number] | null {
  const roster = ENEMY_V7_IDS_BY_WAVE[waveId as EnemyV7WaveId];
  if (!roster) return null;
  return ENEMY_V7_BY_ID[roster[index % roster.length]];
}

export function enemyV7ForId(
  id: string,
): (typeof ENEMY_V7_DEFINITIONS)[number] | null {
  return ENEMY_V7_BY_ID[id as EnemyV7Id] ?? null;
}

export function enemyV7IdsForMission(
  missionId: MissionDefinition["id"],
): readonly EnemyV7Id[] {
  return ENEMY_V7_DEFINITIONS.filter((enemy) => enemy.missionId === missionId).map(
    (enemy) => enemy.id,
  );
}
