import type { SaveGame } from '../types';
import { normalizeSoloV69Campaign, soloV69MatchesSave } from './campaignSoloV69';
import { getChronicleRank } from './clanChronicle';
import { createSoloV70State, normalizeSoloV70State, SOLO_V70_PHASES, SOLO_V70_SIGNS, soloV70Receipts, soloV70Portal, soloV70CanTravel, type SoloV70State, type SoloV70Receipt } from './firstHuntSoloV70';
export interface SoloV70Campaign { version:1;status:'active'|'completed';checkpoint:SoloV70State;receipts:SoloV70Receipt[];startedAt:string;completedAt:string|null }
export type SoloV70Save=SaveGame&{soloV70?:SoloV70Campaign|null};
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const iso=(v:unknown):v is string=>typeof v==='string'&&v.length<=128&&Number.isFinite(Date.parse(v));
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
export function normalizeSoloV70Campaign(v:unknown):SoloV70Campaign|null{if(!record(v)||v.version!==1||!['active','completed'].includes(String(v.status))||!iso(v.startedAt))return null;const checkpoint=normalizeSoloV70State(v.checkpoint);if(!checkpoint||!Array.isArray(v.receipts)||!same(v.receipts,soloV70Receipts(checkpoint)))return null;const complete=checkpoint.phase==='complete';if((v.status==='completed')!==complete||(complete?!iso(v.completedAt)||Date.parse(v.completedAt)<Date.parse(v.startedAt):v.completedAt!==null))return null;return {version:1,status:v.status as SoloV70Campaign['status'],checkpoint,receipts:soloV70Receipts(checkpoint),startedAt:v.startedAt,completedAt:v.completedAt as string|null};}
function prerequisites(v:unknown):v is SoloV70Save {return record(v)&&soloV69MatchesSave(v)&&normalizeSoloV69Campaign(v.soloV69)?.status==='completed'&&getChronicleRank((v as unknown as SoloV70Save).prologue!.chronicle)==='young-blood'&&(v as unknown as SoloV70Save).prologue!.chronicle.rites.length===2;}
const journey=(v:Record<string,unknown>)=>record(v.homeworldRegionV68)&&v.homeworldRegionV68.status!=='at-city'||record(v.homeworldPassageV67)&&v.homeworldPassageV67.status!=='at-city'||record(v.gameReserveV66)&&v.gameReserveV66.status==='active';
export function soloV70MatchesSave(v:unknown){if(!record(v))return false;if(v.soloV70===undefined||v.soloV70===null)return true;const progress=normalizeSoloV70Campaign(v.soloV70);return prerequisites(v)&&!!progress&&!(progress.status==='active'&&journey(v));}
export const canStartSoloV70=(v:unknown)=>record(v)&&prerequisites(v)&&soloV70MatchesSave(v)&&!journey(v);
export function startSoloV70Campaign(save:SoloV70Save,now=new Date().toISOString()):SoloV70Save|null{if(!canStartSoloV70(save)||!iso(now))return null;return save.soloV70?save:{...save,soloV70:{version:1,status:'active',checkpoint:createSoloV70State(),receipts:[],startedAt:now,completedAt:null}};}
function advance(save:SoloV70Save,raw:SoloV70State,incoming:readonly SoloV70Receipt[],now:string):SoloV70Save|null{
 const before=normalizeSoloV70Campaign(save.soloV70),next=normalizeSoloV70State(raw);if(!before||!next||!canStartSoloV70(save)||!iso(now)||Date.parse(now)<Date.parse(before.startedAt))return null;
 const old=before.checkpoint,delta=next.tick-old.tick,op=SOLO_V70_PHASES.indexOf(old.phase),np=SOLO_V70_PHASES.indexOf(next.phase),receipts=soloV70Receipts(next),fresh=receipts.slice(before.receipts.length);
 if(delta<0||np<op||np>op+1||next.phaseStartedAt<old.phaseStartedAt||next.walked<old.walked||next.walked-old.walked>delta*3.5+.1||next.signs<old.signs||next.signs>old.signs+1||next.signals<old.signals||next.signals-old.signals>delta||next.configuration<old.configuration||next.configuration>old.configuration+1||next.liftTicks<old.liftTicks||next.liftTicks-old.liftTicks>Math.max(1,delta)||next.attempts<old.attempts||next.attempts>old.attempts+1||next.drone.hits<old.drone.hits||next.drone.hits>old.drone.hits+1||next.doorCrossings<old.doorCrossings||next.doorCrossings>old.doorCrossings+1||old.visited.some((x,i)=>x&&!next.visited[i])||before.receipts.some((r,i)=>!same(r,receipts[i]))||fresh.length>1||fresh.some(r=>!incoming.some(i=>same(i,r)))||incoming.some(i=>!receipts.some(r=>same(i,r)))||new Set(incoming.map(i=>i.id)).size!==incoming.length||before.status==='completed'&&!same(old,next))return null;
 const near=(room:number,x:number,y=430,t=40)=>next.room===room&&Math.abs(next.player.x-x)<t&&Math.abs(next.player.y-y)<.01;
 if(next.room!==old.room){const side=next.room>old.room?'right':'left',exit=soloV70Portal(old.room,side,old.configuration),entry=soloV70Portal(next.room,side==='right'?'left':'right',next.configuration);if(!soloV70CanTravel(old,next.room)||next.doorCrossings!==old.doorCrossings+1||next.lastDoor?.from!==old.room||next.lastDoor.to!==next.room||next.lastDoor.tick!==next.tick||next.roomEnteredAt!==next.tick||Math.abs(old.player.x-exit.x)>delta*3.5+42||!near(next.room,entry.x,entry.y,1)||next.player.vx!==0||next.player.vy!==0)return null;}
 else if(next.doorCrossings!==old.doorCrossings||!same(next.lastDoor,old.lastDoor)||next.attempts===old.attempts&&Math.abs(next.player.x-old.player.x)>delta*3.5+.1)return null;
 if(next.visited.some((x,i)=>x!==(old.visited[i]||i===next.room))||next.room===old.room&&next.companions.some((c,i)=>Math.abs(c.x-old.companions[i].x)>delta*2.9+.1))return null;
 if(next.signs>old.signs){const p=SOLO_V70_SIGNS[old.signs];if(old.phase!=='signs'||!p||!near(2,p.x,p.y)||next.scan!==0)return null;}
 if(next.companionMode!==old.companionMode&&!['oath','separation'].includes(old.phase)&&!fresh.length)return null;
 if(old.liftTicks===0&&next.liftTicks>0&&(old.phase!=='counterweight'||!near(5,540)))return null;
 if(next.valveTimer>Math.max(0,old.valveTimer-delta)&&(old.phase!=='quarantine'||!near(8,200)||next.valveTimer!==600))return null;
 const retry=next.attempts===old.attempts+1;if(retry){if(old.failedAt===null||next.tick-old.failedAt<90||old.health!==0||next.failedAt!==null||next.health!==6||!near(old.room,125)||next.acid.ttl!==0||next.drone.hits!==old.drone.hits||next.drone.hp!==(old.phase==='drone'?5:old.drone.hp))return null;}
 else if(next.health>old.health||next.drone.hp>old.drone.hp||next.health<old.health-1||next.drone.hp<old.drone.hp-1)return null;
 if(next.drone.hp<old.drone.hp&&(old.phase!=='drone'||next.room!==8||Math.abs(next.player.x-next.drone.x)>=100||next.player.y<=330||next.attackTimer!==18||next.attackCooldown!==45||next.drone.hits!==old.drone.hits+1))return null;
 if(next.configuration!==old.configuration&&!fresh.length)return null;
 if(fresh.length){const id=fresh[0].id;const endpoints:Partial<Record<SoloV70Receipt['id'],[number,number,number]>>={'briefed':[0,160,430],'upper-entry':[0,900,270],'triad-oath':[1,520,430],'signs-read':[2,850,360],'arsenal-opened':[3,820,430],'belvedere-serviced':[4,950,270],'counterweight-aligned':[5,950,300],'human-truce':[6,740,430],'second-configuration':[7,300,430],'triad-rejoined':[7,300,430],'quarantine-valves':[8,980,430],'returned':[0,160,430],'mentor-report':[0,160,430],'opening-attested':[0,160,430]};const target=endpoints[id];if(target&&!near(...target))return null;if(id==='returned'&&next.walked<10000||id==='drone-confined'&&(next.room!==8||next.drone.hp!==0||next.drone.hits<5)||id==='triad-oath'&&!next.companions.every((c,i)=>Math.abs(c.x-[320,730][i])<5)||id==='triad-rejoined'&&!next.companions.every((c,i)=>Math.abs(c.x-[520,920][i])<5))return null;}
 const complete=next.phase==='complete',soloV70:SoloV70Campaign={...before,checkpoint:next,receipts,status:complete?'completed':'active',completedAt:complete?before.completedAt??now:null};if(!normalizeSoloV70Campaign(soloV70))return null;
 // A real local drone combat is retained here, but is not an invented global
 // rite, Queen kill, triad blooding, permanent armament or personal ship grant.
 return {...save,soloV70,profile:{...save.profile,playTimeSeconds:save.profile.playTimeSeconds+Math.max(0,Math.floor(next.tick/60)-Math.floor(old.tick/60))}};
}
export const withSoloV70Checkpoint=(save:SoloV70Save,state:SoloV70State,now=new Date().toISOString())=>advance(save,state,[],now);
export const withSoloV70Progress=(save:SoloV70Save,receipts:readonly SoloV70Receipt[],state:SoloV70State,now=new Date().toISOString())=>advance(save,state,receipts,now);
export const soloV70NeedsScene=(progress:SoloV70Campaign|null|undefined)=>progress?.status==='active';
